"""Self-check for the schema extractor, and a regression guard against the
exact bug that made hypr2lua's own stub parser extract zero entries: a naive
line filter that treats every "---"-prefixed line as a comment to skip,
when in LuaLS files "---" is the annotation marker, not a comment.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from hyprvalidate.schema.extractor import extract, extract_file, Schema

STUB_PATH = "/usr/share/hypr/stubs/hl.meta.lua"

FIXTURE = '''
-- This file is autogenerated. Do not edit by hand.
---@meta

---@alias HL.EventName
---| "hyprland.start"
---| "window.open"

---@class HL.BindOptions
---@field repeating? boolean
---@field release? boolean
---@field device? {inclusive?: boolean, list?: string[]}
local __HL_BindOptions = {}

---@class HL.ConfigValueTypes
---@field ['animations.enabled'] boolean
---@field ['general.gaps_in'] integer|HL.CssGap
local __HL_ConfigValueTypes = {}

---@alias HL.Gradient string|{colors:string[], angle?:number}

---@class HL.DspWindowNamespace
---@field close fun(...): HL.Dispatcher
---@field float fun(...): HL.Dispatcher
local __HL_DspWindowNamespace = {}
'''


def test_classes_and_fields():
    schema = extract(FIXTURE)
    assert "HL.BindOptions" in schema.classes
    opts = schema.classes["HL.BindOptions"].fields
    assert opts["repeating"] == "boolean"
    assert opts["release"] == "boolean"
    assert opts["device"] == "{inclusive?: boolean, list?: string[]}"


def test_bracketed_fields_populate_config_value_types():
    schema = extract(FIXTURE)
    assert schema.config_value_types["animations.enabled"] == "boolean"
    assert schema.config_value_types["general.gaps_in"] == "integer|HL.CssGap"


def test_union_alias_literals():
    schema = extract(FIXTURE)
    ev = schema.aliases["HL.EventName"]
    assert ev.literals == ["hyprland.start", "window.open"]
    assert ev.type_expr is None


def test_simple_type_alias_has_no_literals():
    schema = extract(FIXTURE)
    grad = schema.aliases["HL.Gradient"]
    assert grad.literals == []
    assert grad.type_expr == "string|{colors:string[], angle?:number}"


def test_dispatcher_namespace_fields():
    schema = extract(FIXTURE)
    win = schema.classes["HL.DspWindowNamespace"].fields
    assert win["close"] == "fun(...): HL.Dispatcher"
    assert win["float"] == "fun(...): HL.Dispatcher"


def test_non_annotation_lines_are_never_mistaken_for_data():
    """Regression guard for hypr2lua's exact bug: a state machine that skips
    ALL '---'-prefixed lines would see 0 classes and 0 aliases here, same as
    it did against the real 1770-line stub."""
    schema = extract(FIXTURE)
    assert len(schema.classes) > 0
    assert len(schema.aliases) > 0


def test_refuses_to_report_success_on_truly_empty_input():
    schema = extract("-- just a comment file\nlocal x = 1\n")
    assert len(schema.classes) == 0
    assert len(schema.aliases) == 0
    # extractor.py's main() treats this combination as a hard error (see
    # the empty-schema check there) rather than silently "succeeding" -
    # that check is exercised at the CLI layer, not here.


def test_from_json_round_trips_to_json():
    """Needed for consumers that can't read the stub directly (e.g. a
    browser demo) - they load a frozen to_json() snapshot instead."""
    assert Path(STUB_PATH).is_file(), f"expected the installed stub at {STUB_PATH}"
    schema = extract_file(STUB_PATH)
    restored = Schema.from_json(schema.to_json())
    assert restored.classes == schema.classes
    assert restored.aliases == schema.aliases
    assert restored.config_value_types == schema.config_value_types


if __name__ == "__main__":
    for name, fn in list(globals().items()):
        if name.startswith("test_"):
            fn()
            print(f"ok  {name}")
    print("all tests passed")
