"""Builds site/bundle.js - a JS module embedding this project's pure-Python
source (base64, to sidestep backtick/${} escaping in the source itself) plus
the frozen schema snapshot, for the in-browser Pyodide demo.

The demo can't read /usr/share/hypr/stubs/hl.meta.lua from a visitor's
machine, and can't shell out to luac (no such binary in a browser) - so it
runs the real converter + checker Python modules against a frozen
schema.json snapshot, skipping only the luac gate step. Re-run this after
any change to the modules listed in MODULES or to schema.json.
"""
import base64
import json
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent

MODULES = [
    "hyprvalidate/schema/extractor.py",
    "hyprvalidate/hyprlang/lexer.py",
    "hyprvalidate/hyprlang/parser.py",
    "hyprvalidate/luaast/reader.py",
    "hyprvalidate/luaast/writer.py",
    "hyprvalidate/checker.py",
    "hyprvalidate/converter/dispatch.py",
    "hyprvalidate/converter/coerce.py",
    "hyprvalidate/converter/rename.py",
    "hyprvalidate/converter/todo.py",
    "hyprvalidate/converter/mapper.py",
]


def b64(path: Path) -> str:
    return base64.b64encode(path.read_bytes()).decode("ascii")


def main():
    files = {mod: b64(REPO_ROOT / mod) for mod in MODULES}
    schema_b64 = b64(REPO_ROOT / "schema.json")

    out = REPO_ROOT / "site" / "bundle.js"
    out.write_text(
        "// Generated by site/build_bundle.py - do not edit by hand.\n"
        f"export const PY_FILES = {json.dumps(files)};\n"
        f"export const SCHEMA_JSON_B64 = {json.dumps(schema_b64)};\n"
    )
    total = sum(len(v) for v in files.values()) + len(schema_b64)
    print(f"wrote {out} ({total} base64 chars, {len(files)} modules)")


if __name__ == "__main__":
    main()
