"""Extract a machine-readable schema from Hyprland's LuaLS type stub.

The stub (installed at /usr/share/hypr/stubs/hl.meta.lua, autogenerated by
Hyprland's own build from meta/generateLuaStubs.py) is ~93% LuaLS annotation
comments (`---@class`, `---@field`, `---@alias`, `---| "literal"`). None of
the four existing hyprlang->lua converters read it correctly:
  - hyprconf2lua, hypr-migrate: never attempt to.
  - hypr2lua: loads it, but its parser skips every line starting with "--"
    (parser.go:29) - which is every LuaLS annotation - and extracts 0 entries.

This is a state machine, not that: it reads ONLY "---"-prefixed lines and
tracks what block it's currently inside.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field, asdict
from pathlib import Path


@dataclass
class ClassInfo:
    name: str
    fields: dict[str, str] = field(default_factory=dict)  # field name -> type expr


@dataclass
class AliasInfo:
    name: str
    literals: list[str] = field(default_factory=list)      # for string-union aliases
    type_expr: str | None = None                            # for `---@alias X Y` form


@dataclass
class Schema:
    classes: dict[str, ClassInfo] = field(default_factory=dict)
    aliases: dict[str, AliasInfo] = field(default_factory=dict)
    config_value_types: dict[str, str] = field(default_factory=dict)  # 'a.b.c' -> type

    def to_json(self) -> str:
        return json.dumps(
            {
                "classes": {k: asdict(v) for k, v in self.classes.items()},
                "aliases": {k: asdict(v) for k, v in self.aliases.items()},
                "config_value_types": self.config_value_types,
            },
            indent=2,
            sort_keys=True,
        )

    @classmethod
    def from_json(cls, text: str) -> "Schema":
        """Reconstruct a Schema from to_json()'s output - the inverse.
        Exists for consumers that can't read the stub directly (e.g. a
        browser environment with no filesystem access to
        /usr/share/hypr/stubs), so they can load a frozen snapshot instead
        of re-parsing hl.meta.lua."""
        data = json.loads(text)
        return cls(
            classes={k: ClassInfo(**v) for k, v in data.get("classes", {}).items()},
            aliases={k: AliasInfo(**v) for k, v in data.get("aliases", {}).items()},
            config_value_types=data.get("config_value_types", {}),
        )


# ---@class Name[: Parent]
_RE_CLASS = re.compile(r'^---@class\s+([\w.]+)')

# ---@field name type...          (bare identifier field name)
# ---@field ['dotted.key'] type... (bracketed/quoted field name, used for
#                                    ConfigValueTypes-style maps)
_RE_FIELD_BARE = re.compile(r"^---@field\s+(\w+\??)\s+(.+)$")
_RE_FIELD_BRACKET = re.compile(r"^---@field\s+\[(['\"])(.+?)\1\]\s+(.+)$")

# ---@alias Name [TypeExpr]   (TypeExpr present => simple alias, absent => a
#                               following run of `---| "literal"` lines defines it)
_RE_ALIAS = re.compile(r'^---@alias\s+([\w.]+)(?:\s+(.+))?$')

# ---| "literal-value"   (continuation line for a union alias)
_RE_UNION_MEMBER = re.compile(r'^---\|\s*"([^"]*)"')


def extract(text: str) -> Schema:
    schema = Schema()

    current_class: ClassInfo | None = None
    current_alias: AliasInfo | None = None

    for raw_line in text.splitlines():
        line = raw_line.strip()

        if not line.startswith("---") and not line.startswith("---|"):
            # Any non-annotation line (blank, code, `local __HL_X = {}`, `hl = {}`)
            # ends whatever class/alias block we were accumulating.
            current_class = None
            current_alias = None
            continue

        if m := _RE_CLASS.match(line):
            name = m.group(1)
            current_class = schema.classes.setdefault(name, ClassInfo(name=name))
            current_alias = None
            continue

        if m := _RE_ALIAS.match(line):
            name, type_expr = m.group(1), m.group(2)
            current_alias = schema.aliases.setdefault(name, AliasInfo(name=name))
            if type_expr:
                current_alias.type_expr = type_expr.strip()
            current_class = None
            continue

        if current_class is not None:
            if m := _RE_FIELD_BRACKET.match(line):
                key, type_expr = m.group(2), m.group(3).strip()
                current_class.fields[key] = type_expr
                if current_class.name == "HL.ConfigValueTypes":
                    schema.config_value_types[key] = type_expr
                continue
            if m := _RE_FIELD_BARE.match(line):
                fname, type_expr = m.group(1), m.group(2).strip()
                current_class.fields[fname.rstrip("?")] = type_expr
                continue
            # A `---` comment line inside a class that isn't a @field (e.g. a
            # plain doc comment) - ignore, stay in the class.
            continue

        if current_alias is not None:
            if m := _RE_UNION_MEMBER.match(line):
                current_alias.literals.append(m.group(1))
                continue
            continue

    return schema


def extract_file(path: str | Path) -> Schema:
    return extract(Path(path).read_text())


def load_schema(path: str | Path) -> Schema:
    """Load a schema from either Hyprland's `.lua` stub or a `.json`
    snapshot produced by `Schema.to_json()`.

    The JSON path exists so a config can be validated on a machine that
    doesn't have Hyprland installed at all - CI for a dotfiles repo, a
    container, or the browser demo. Dispatch is on the file extension,
    since the two formats are unambiguous.
    """
    p = Path(path)
    if p.suffix == ".json":
        return Schema.from_json(p.read_text())
    return extract_file(p)


def main() -> None:
    import argparse

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "stub", nargs="?", default="/usr/share/hypr/stubs/hl.meta.lua",
        help="path to hl.meta.lua (default: the installed system stub)",
    )
    ap.add_argument("-o", "--out", help="write JSON here instead of stdout")
    args = ap.parse_args()

    stub_path = Path(args.stub)
    if not stub_path.is_file():
        raise SystemExit(
            f"error: stub file not found at {stub_path}\n"
            "This tool reads Hyprland's own autogenerated LuaLS stub. "
            "If your distro doesn't ship it at the default path, pass it explicitly."
        )

    schema = extract_file(stub_path)

    # Hard failure on empty extraction - this is the exact bug that let
    # hypr2lua ship a schema loader that silently extracts nothing.
    if not schema.classes and not schema.aliases:
        raise SystemExit(
            f"error: extracted ZERO classes/aliases from {stub_path} - "
            "the stub format has likely changed and this extractor needs updating. "
            "Refusing to produce an empty schema silently."
        )

    out = schema.to_json()
    if args.out:
        Path(args.out).write_text(out + "\n")
        print(f"wrote schema ({len(schema.classes)} classes, {len(schema.aliases)} aliases) to {args.out}")
    else:
        print(out)


if __name__ == "__main__":
    main()
