"""CLI. `check` validates an existing .lua config; `convert` turns an old
hyprlang .conf into Lua using the schema-driven mapper.

Exit codes, distinct so scripts/CI can tell "your file is broken" from
"your file has schema issues" apart:
  0 - clean
  1 - schema findings (unknown symbol/key, type mismatch) - for `convert`,
      this means the CONVERTED output has findings (which may legitimately
      reflect an un-coercible value in the *original* file, not a
      converter bug - see the "converted but flagged" case in the module
      docstring of converter/mapper.py)
  2 - a file failed the luac gate (not valid Lua at all), or (for
      `convert`) the input hyprlang file itself failed to parse, or the
      converter's own output failed the luac gate (that specific case IS
      a converter bug, never handed to the user silently)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from hyprvalidate.luaast import reader, luac_gate
from hyprvalidate.luaast.luac_gate import LuacNotFound
from hyprvalidate.hyprlang import parser as hyprlang_parser
from hyprvalidate.converter import mapper
from hyprvalidate.schema.extractor import load_schema
from hyprvalidate import checker, fixer

DEFAULT_STUB_PATH = "/usr/share/hypr/stubs/hl.meta.lua"


def _version() -> str:
    from importlib.metadata import version, PackageNotFoundError

    try:
        return version("hyprvalidate")
    except PackageNotFoundError:  # running from a source checkout
        return "0.1.0+source"


def _expand_paths(paths: list[Path]) -> tuple[list[Path], list[str]]:
    """Expand any directory argument into the .lua files it contains, so a
    modular config (from `convert --split`, or hand-written) can be checked
    with one command. Returns (files, errors)."""
    expanded: list[Path] = []
    errors: list[str] = []
    for path in paths:
        if path.is_dir():
            found = sorted(path.glob("*.lua"))
            if not found:
                errors.append(f"error: no .lua files found in {path}")
            expanded.extend(found)
        else:
            expanded.append(path)
    return expanded, errors


def check_files(paths: list[Path], stub_path: str, fix: bool = False) -> tuple[int, list[str]]:
    """Pure orchestration, no I/O to stdout (beyond overwriting a file
    in-place when `fix` finds something to fix) - kept separate from main()
    so it's directly testable without subprocess/capsys."""
    lines: list[str] = []

    if not Path(stub_path).is_file():
        return 2, [
            f"error: schema not found at {stub_path}",
            "This tool reads Hyprland's own autogenerated LuaLS stub. Pass "
            "--stub to point at it explicitly if your install differs, or "
            "point it at a schema.json snapshot to run without Hyprland "
            "installed at all.",
        ]

    paths, path_errors = _expand_paths(paths)
    if path_errors:
        return 2, path_errors

    schema = load_schema(stub_path)

    syntax_failed = False
    schema_findings_total = 0
    fixed_total = 0

    for path in paths:
        luac_result = luac_gate.check_file(path)
        if not luac_result.ok:
            syntax_failed = True
            lines.append(f"{luac_result.message}")
            continue

        source = path.read_text()
        tree = reader.parse(source)
        findings = checker.check(schema, tree)

        if fix and any(f.fix is not None for f in findings):
            result = fixer.apply_fixes(source, findings)
            # Paranoia matching convert's own discipline: never write a
            # patched file without first confirming the patch itself is
            # valid Lua and re-validating against the schema - a fix that
            # broke syntax, or that (like inserting `()` on a dispatcher
            # that turns out to need arguments) reveals a fresh problem, is
            # reported, not silently written over.
            luac_patched = luac_gate.check_source(result.source)
            if not luac_patched.ok:
                return 2, [
                    f"error: applying fixes to {path} produced invalid Lua - "
                    "this is a hyprvalidate bug, please report it:",
                    luac_patched.message or "",
                ]
            path.write_text(result.source)
            fixed_total += len(result.applied)
            lines.append(f"{path}: fixed {len(result.applied)} issue(s)")
            for f in result.applied:
                lines.append(f"  [{f.kind.value}] {f.message}")
            findings = checker.check_source(schema, result.source)

        schema_findings_total += len(findings)
        for f in sorted(findings, key=lambda f: (f.line or 0)):
            lines.append(f"{path}:{f.line}: [{f.kind.value}] {f.message}")

    if syntax_failed:
        return 2, lines
    if fixed_total:
        lines.append(f"\nfixed {fixed_total} issue(s).")
    if schema_findings_total:
        lines.append(f"\n{schema_findings_total} issue(s) found.")
        return 1, lines

    lines.append(f"{len(paths)} file(s) checked, no issues found.")
    return 0, lines


def convert_file(
    path: Path, stub_path: str, output: Path | None, split: Path | None = None
) -> tuple[int, list[str]]:
    """Pure orchestration, no I/O beyond writing `output` if given - kept
    separate from main() so it's directly testable without subprocess/
    capsys, same shape as check_files()."""
    lines: list[str] = []

    if not Path(stub_path).is_file():
        return 2, [
            f"error: schema not found at {stub_path}",
            "This tool reads Hyprland's own autogenerated LuaLS stub. Pass "
            "--stub to point at it explicitly if your install differs, or "
            "point it at a schema.json snapshot to run without Hyprland "
            "installed at all.",
        ]

    schema = load_schema(stub_path)

    try:
        hf = hyprlang_parser.parse_file(path)
    except hyprlang_parser.ParseError as exc:
        return 2, [f"error: {path} failed to parse as hyprlang: {exc}"]

    if split is not None:
        return _emit_split(schema, hf, split, lines)

    lua_source = mapper.convert(schema, hf)

    luac_result = luac_gate.check_source(lua_source)
    if not luac_result.ok:
        return 2, [
            "error: the converter's own output failed the luac gate - this is a "
            "converter bug, please report it:",
            luac_result.message or "",
        ]

    if output is not None:
        output.write_text(lua_source)
        lines.append(f"wrote {output}")
    else:
        lines.append(lua_source)

    findings = checker.check_source(schema, lua_source)
    if findings:
        lines.append("")
        for f in sorted(findings, key=lambda f: (f.line or 0)):
            lines.append(f"{output or path}:{f.line}: [{f.kind.value}] {f.message}")
        lines.append(f"\n{len(findings)} issue(s) found in the converted output.")
        return 1, lines

    return 0, lines


def _emit_split(schema, hf, split: Path, lines: list[str]) -> tuple[int, list[str]]:
    """Convert into a directory of modular files. Every emitted file is run
    through the luac gate and the full checker before anything is written -
    a converter that produces broken Lua shouldn't leave a half-written
    directory behind."""
    files = mapper.convert_split(schema, hf)

    for name, src in sorted(files.items()):
        luac_result = luac_gate.check_source(src)
        if not luac_result.ok:
            return 2, [
                f"error: the converter's own output for {name} failed the luac gate - "
                "this is a converter bug, please report it:",
                luac_result.message or "",
            ]

    split.mkdir(parents=True, exist_ok=True)
    for name, src in sorted(files.items()):
        (split / name).write_text(src)

    entry = split / f"{mapper.M_ENTRY}.lua"
    lines.append(f"wrote {len(files)} file(s) to {split}/ (entry point: {entry.name})")
    for name in sorted(files):
        lines.append(f"  {name}")

    findings = []
    for name, src in sorted(files.items()):
        for f in checker.check_source(schema, src):
            findings.append((name, f))

    if findings:
        lines.append("")
        for name, f in findings:
            lines.append(f"{split / name}:{f.line}: [{f.kind.value}] {f.message}")
        lines.append(f"\n{len(findings)} issue(s) found in the converted output.")
        return 1, lines

    return 0, lines


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="hyprvalidate",
        description="Schema-driven validator for Hyprland's Lua config format.",
    )
    parser.add_argument(
        "--version", action="version", version=f"hyprvalidate {_version()}"
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    check_parser = subparsers.add_parser(
        "check", help="check one or more .lua config files against the real Hyprland API"
    )
    check_parser.add_argument("files", nargs="+", type=Path, help=".lua file(s) to check")
    check_parser.add_argument(
        "--stub", default=DEFAULT_STUB_PATH,
        help=(
            "path to Hyprland's hl.meta.lua stub, or a schema.json snapshot "
            f"to run without Hyprland installed (default: {DEFAULT_STUB_PATH})"
        ),
    )
    check_parser.add_argument(
        "--fix", action="store_true",
        help=(
            "apply the unambiguous fixes in place (missing quotes, uncalled "
            "dispatcher factories) and re-check; findings with no single "
            "correct fix (unknown symbols/keys, type/arity mismatches, "
            "duplicate binds) are still reported, never guessed at"
        ),
    )

    convert_parser = subparsers.add_parser(
        "convert", help="convert an old hyprlang .conf file into Lua"
    )
    convert_parser.add_argument("file", type=Path, help=".conf file to convert")
    convert_parser.add_argument(
        "--stub", default=DEFAULT_STUB_PATH,
        help=(
            "path to Hyprland's hl.meta.lua stub, or a schema.json snapshot "
            f"to run without Hyprland installed (default: {DEFAULT_STUB_PATH})"
        ),
    )
    convert_parser.add_argument(
        "-o", "--output", type=Path, default=None,
        help="write the converted Lua to this file instead of stdout",
    )
    convert_parser.add_argument(
        "--split", type=Path, default=None, metavar="DIR",
        help="write modular files (one per config area) into DIR, with a "
             "hyprland.lua entry point that require()s them",
    )

    args = parser.parse_args(argv)

    if args.command == "check":
        try:
            exit_code, lines = check_files(args.files, args.stub, args.fix)
        except LuacNotFound as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 2
        for line in lines:
            print(line)
        return exit_code

    if args.command == "convert":
        try:
            exit_code, lines = convert_file(
                args.file, args.stub, args.output, args.split
            )
        except LuacNotFound as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 2
        for line in lines:
            print(line)
        return exit_code

    parser.error(f"unknown command {args.command!r}")
    return 2


if __name__ == "__main__":
    sys.exit(main())
