"""CLI (docs/PLAN.md row 8). `check` validates an existing .lua config;
`convert` (docs/CONVERTER_PLAN.md task 7.5) turns an old hyprlang .conf
into Lua using the schema-driven mapper (rows 5-7).

Exit codes, distinct so scripts/CI can tell "your file is broken" from
"your file has schema issues" apart:
  0 - clean
  1 - schema findings (unknown symbol/key, type mismatch) - for `convert`,
      this means the CONVERTED output has findings (which may legitimately
      reflect an un-coercible value in the *original* file, not a
      converter bug - see the "converted but flagged" case in the module
      docstring of converter/mapper.py)
  2 - a file failed the luac gate (not valid Lua at all), or (for
      `convert`) the input hyprlang file itself failed to parse, or the
      converter's own output failed the luac gate (that specific case IS
      a converter bug, never handed to the user silently)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from hyprvalidate.luaast import reader, luac_gate
from hyprvalidate.hyprlang import parser as hyprlang_parser
from hyprvalidate.converter import mapper
from hyprvalidate.schema.extractor import extract_file
from hyprvalidate import checker

DEFAULT_STUB_PATH = "/usr/share/hypr/stubs/hl.meta.lua"


def check_files(paths: list[Path], stub_path: str) -> tuple[int, list[str]]:
    """Pure orchestration, no I/O to stdout - kept separate from main() so
    it's directly testable without subprocess/capsys."""
    lines: list[str] = []

    if not Path(stub_path).is_file():
        return 2, [
            f"error: schema stub not found at {stub_path}",
            "This tool reads Hyprland's own autogenerated LuaLS stub - "
            "pass --stub to point at it explicitly if your install differs.",
        ]

    schema = extract_file(stub_path)

    syntax_failed = False
    schema_findings_total = 0

    for path in paths:
        luac_result = luac_gate.check_file(path)
        if not luac_result.ok:
            syntax_failed = True
            lines.append(f"{luac_result.message}")
            continue

        tree = reader.parse_file(path)
        findings = checker.check(schema, tree)
        schema_findings_total += len(findings)
        for f in sorted(findings, key=lambda f: (f.line or 0)):
            lines.append(f"{path}:{f.line}: [{f.kind.value}] {f.message}")

    if syntax_failed:
        return 2, lines
    if schema_findings_total:
        lines.append(f"\n{schema_findings_total} issue(s) found.")
        return 1, lines

    lines.append(f"{len(paths)} file(s) checked, no issues found.")
    return 0, lines


def convert_file(path: Path, stub_path: str, output: Path | None) -> tuple[int, list[str]]:
    """Pure orchestration, no I/O beyond writing `output` if given - kept
    separate from main() so it's directly testable without subprocess/
    capsys, same shape as check_files()."""
    lines: list[str] = []

    if not Path(stub_path).is_file():
        return 2, [
            f"error: schema stub not found at {stub_path}",
            "This tool reads Hyprland's own autogenerated LuaLS stub - "
            "pass --stub to point at it explicitly if your install differs.",
        ]

    schema = extract_file(stub_path)

    try:
        hf = hyprlang_parser.parse_file(path)
    except hyprlang_parser.ParseError as exc:
        return 2, [f"error: {path} failed to parse as hyprlang: {exc}"]

    lua_source = mapper.convert(schema, hf)

    luac_result = luac_gate.check_source(lua_source)
    if not luac_result.ok:
        return 2, [
            "error: the converter's own output failed the luac gate - this is a "
            "converter bug, please report it:",
            luac_result.message or "",
        ]

    if output is not None:
        output.write_text(lua_source)
        lines.append(f"wrote {output}")
    else:
        lines.append(lua_source)

    findings = checker.check_source(schema, lua_source)
    if findings:
        lines.append("")
        for f in sorted(findings, key=lambda f: (f.line or 0)):
            lines.append(f"{output or path}:{f.line}: [{f.kind.value}] {f.message}")
        lines.append(f"\n{len(findings)} issue(s) found in the converted output.")
        return 1, lines

    return 0, lines


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="hyprvalidate",
        description="Schema-driven validator for Hyprland's Lua config format.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    check_parser = subparsers.add_parser(
        "check", help="check one or more .lua config files against the real Hyprland API"
    )
    check_parser.add_argument("files", nargs="+", type=Path, help=".lua file(s) to check")
    check_parser.add_argument(
        "--stub", default=DEFAULT_STUB_PATH,
        help=f"path to Hyprland's hl.meta.lua stub (default: {DEFAULT_STUB_PATH})",
    )

    convert_parser = subparsers.add_parser(
        "convert", help="convert an old hyprlang .conf file into Lua"
    )
    convert_parser.add_argument("file", type=Path, help=".conf file to convert")
    convert_parser.add_argument(
        "--stub", default=DEFAULT_STUB_PATH,
        help=f"path to Hyprland's hl.meta.lua stub (default: {DEFAULT_STUB_PATH})",
    )
    convert_parser.add_argument(
        "-o", "--output", type=Path, default=None,
        help="write the converted Lua to this file instead of stdout",
    )

    args = parser.parse_args(argv)

    if args.command == "check":
        exit_code, lines = check_files(args.files, args.stub)
        for line in lines:
            print(line)
        return exit_code

    if args.command == "convert":
        exit_code, lines = convert_file(args.file, args.stub, args.output)
        for line in lines:
            print(line)
        return exit_code

    parser.error(f"unknown command {args.command!r}")
    return 2


if __name__ == "__main__":
    sys.exit(main())
