"""CLI (docs/PLAN.md row 8). Only `check` exists - `convert` needs rows 5-7
(hyprlang reader, Lua writer, schema-driven mapper), none of which exist
yet. Not stubbing it ahead of time.

Exit codes, distinct so scripts/CI can tell "your file is broken" from
"your file has schema issues" apart:
  0 - clean
  1 - schema findings (unknown symbol/key, type mismatch)
  2 - a file failed the luac gate (not valid Lua at all)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from hyprvalidate.luaast import reader, luac_gate
from hyprvalidate.schema.extractor import extract_file
from hyprvalidate import checker

DEFAULT_STUB_PATH = "/usr/share/hypr/stubs/hl.meta.lua"


def check_files(paths: list[Path], stub_path: str) -> tuple[int, list[str]]:
    """Pure orchestration, no I/O to stdout - kept separate from main() so
    it's directly testable without subprocess/capsys."""
    lines: list[str] = []

    if not Path(stub_path).is_file():
        return 2, [
            f"error: schema stub not found at {stub_path}",
            "This tool reads Hyprland's own autogenerated LuaLS stub - "
            "pass --stub to point at it explicitly if your install differs.",
        ]

    schema = extract_file(stub_path)

    syntax_failed = False
    schema_findings_total = 0

    for path in paths:
        luac_result = luac_gate.check_file(path)
        if not luac_result.ok:
            syntax_failed = True
            lines.append(f"{luac_result.message}")
            continue

        tree = reader.parse_file(path)
        findings = checker.check(schema, tree)
        schema_findings_total += len(findings)
        for f in sorted(findings, key=lambda f: (f.line or 0)):
            lines.append(f"{path}:{f.line}: [{f.kind.value}] {f.message}")

    if syntax_failed:
        return 2, lines
    if schema_findings_total:
        lines.append(f"\n{schema_findings_total} issue(s) found.")
        return 1, lines

    lines.append(f"{len(paths)} file(s) checked, no issues found.")
    return 0, lines


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="hyprvalidate",
        description="Schema-driven validator for Hyprland's Lua config format.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    check_parser = subparsers.add_parser(
        "check", help="check one or more .lua config files against the real Hyprland API"
    )
    check_parser.add_argument("files", nargs="+", type=Path, help=".lua file(s) to check")
    check_parser.add_argument(
        "--stub", default=DEFAULT_STUB_PATH,
        help=f"path to Hyprland's hl.meta.lua stub (default: {DEFAULT_STUB_PATH})",
    )

    args = parser.parse_args(argv)

    if args.command == "check":
        exit_code, lines = check_files(args.files, args.stub)
        for line in lines:
            print(line)
        return exit_code

    parser.error(f"unknown command {args.command!r}")
    return 2


if __name__ == "__main__":
    sys.exit(main())
